#!/usr/bin/env python3
"""Install a local snapshot of this standard into a downstream project.

This helper is intentionally conservative. It copies selected standard files
from the current checkout into a target project's `.ai/managed` directory and
generates starter adapter files when they do not already exist.
"""

import argparse
import datetime as dt
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


ENTRY_TEMPLATES = [
    ("AGENTS.md", "adapters/codex/AGENTS.md.template"),
    ("CLAUDE.md", "adapters/claude-code/CLAUDE.md.template"),
]


def copy_tree(source, destination):
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)


def write_if_missing(path, content, written=None, preserved=None):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content, encoding="utf-8")
        if written is not None:
            written.append(str(path))
    elif preserved is not None:
        preserved.append(str(path))


def install_github_templates(project_dir, written, preserved):
    template_root = ROOT / "templates" / "github"
    for template in template_root.rglob("*"):
        if template.is_file():
            target = project_dir / ".github" / template.relative_to(template_root)
            write_if_missing(
                target,
                template.read_text(encoding="utf-8"),
                written=written,
                preserved=preserved,
            )


def write_adoption_report(project_dir, mode, profiles, written, preserved):
    if mode != "existing":
        return

    report_path = project_dir / ".ai" / "adoption" / "REPORT.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# AI Development Standard Adoption Report",
        "",
        "This report was generated by `scripts/init-project.py --mode existing`.",
        "",
        "## Installed Profiles",
        "",
    ]
    lines.extend("- " + profile for profile in profiles)
    lines.extend(
        [
            "",
            "## Files Written",
            "",
        ]
    )
    if written:
        lines.extend("- " + path for path in written)
    else:
        lines.append("- none")
    lines.extend(
        [
            "",
            "## Existing Files Preserved",
            "",
        ]
    )
    if preserved:
        lines.extend("- " + path for path in preserved)
    else:
        lines.append("- none")
    lines.extend(
        [
            "",
            "## Required Manual Review",
            "",
            "- Confirm `.ai/project/COMMANDS.yml` contains real project commands or tracked TODO exceptions.",
            "- Confirm `.ai/project/AI_HISTORY.yml` keeps runtime evidence disabled or local-only until privacy approval exists.",
            "- Confirm `AGENTS.md`, `CLAUDE.md`, and `.kiro/steering/**` reference `.ai/managed` and `.ai/project`.",
            "- Merge standard PR template sections into existing PR templates when preserved.",
            "- Merge standard issue forms into existing issue templates when preserved.",
            "- Align `.ai/project/OWNERS.yml` with CODEOWNERS when ownership is enforced.",
            "- Defer new branch rules until required checks are stable.",
            "",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-dir", required=True)
    parser.add_argument("--repository", default="Eruhitsuji/ai-development-standard")
    parser.add_argument("--commit", required=True)
    parser.add_argument("--profiles", nargs="+", default=["core"])
    parser.add_argument("--mode", choices=["new", "existing"], default="new")
    parser.add_argument(
        "--install-github-templates",
        action="store_true",
        help="Copy GitHub issue and pull request templates when targets are missing.",
    )
    args = parser.parse_args()

    project_dir = Path(args.project_dir).resolve()
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    managed = project_dir / ".ai" / "managed"
    managed.mkdir(parents=True, exist_ok=True)
    written = []
    preserved = []

    copy_tree(ROOT / "standards" / "core", managed / "core")
    written.append(str(managed / "core"))

    profiles_dir = managed / "profiles"
    profiles_dir.mkdir(parents=True, exist_ok=True)
    for profile in args.profiles:
        if profile == "core":
            continue
        source = ROOT / "standards" / "profiles" / profile
        if not source.is_dir():
            raise SystemExit(f"Unknown profile: {profile}")
        copy_tree(source, profiles_dir / profile)
        written.append(str(profiles_dir / profile))

    copy_tree(ROOT / "agents", managed / "agents")
    written.append(str(managed / "agents"))

    lock = f"""schema_version: 1

standard:
  repository: {args.repository}
  version: {version}
  commit: {args.commit}

profiles:
{chr(10).join(f"  - {profile}" for profile in args.profiles)}

adapter_versions:
  codex: {version}
  claude_code: {version}
  kiro: {version}

installed_at: {dt.datetime.now(dt.timezone.utc).isoformat()}
"""
    (project_dir / ".ai" / "standard.lock.yml").write_text(lock, encoding="utf-8")
    written.append(str(project_dir / ".ai" / "standard.lock.yml"))

    template_root = ROOT / "templates" / "downstream"
    for template in template_root.rglob("*"):
        if template.is_file() and template.name != ".gitkeep":
            relative_template = template.relative_to(template_root)
            if str(relative_template).replace("\\", "/") == ".ai/standard.lock.yml":
                continue
            target = project_dir / relative_template
            write_if_missing(
                target,
                template.read_text(encoding="utf-8"),
                written=written,
                preserved=preserved,
            )

    for target_name, template_name in ENTRY_TEMPLATES:
        write_if_missing(
            project_dir / target_name,
            (ROOT / template_name).read_text(encoding="utf-8"),
            written=written,
            preserved=preserved,
        )

    for template in (ROOT / "adapters" / "kiro" / "steering").glob("*.template"):
        name = template.name
        if name.endswith(".template"):
            name = name[: -len(".template")]
        target = project_dir / ".kiro" / "steering" / name
        write_if_missing(
            target,
            template.read_text(encoding="utf-8"),
            written=written,
            preserved=preserved,
        )

    if args.install_github_templates:
        install_github_templates(project_dir, written, preserved)

    write_adoption_report(project_dir, args.mode, args.profiles, written, preserved)

    print(f"Installed standard {version} into {project_dir}")
    if args.mode == "existing":
        print("Existing files were preserved. Review .ai/adoption/REPORT.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
